### ISSUE TITLE
v0.2.0

### ISSUE THREAD

**Issue by icorbrey** [icorbrey/trackinator#14]
## Features

* [ ] Listen for commands within issue comments
* [ ] Listen for commands within pull request comments
* [ ] React to comments within issues
* [ ] React to comments within pull requests
